version: "2"

linters:
  default: all

  disable:
    - depguard          # stdlibだけに限定できないので無効化
    - testpackage       # テストを同一パッケージに入れることにするので無効化
    - wrapcheck         # 便利そうだけど、wrapは使わないので、stacktrace使うので、無効化
    - wsl               # うるさ過ぎるので無効化
    - gosmopolitan      # 日本語リテラルを許可したいので、無効化
    - gochecknoinits    # cli では、inits functions は便利なので無効化
    - varnamelen        # スコープが狭い変数は短い名前にすべきなので無効化
    - godot             # 日本語のコメントはピリオドを使用しないので無効化
    - gochecknoglobals  # global 変数を使用してもいいので無効化
    - revive            # 現状のスタイルは必要なものだけ書く文化なので無効化
    - ireturn           # ジェネリクスを使っているので無効化


  settings:
    errcheck:
      check-type-assertions: true
    forbidigo:
      forbid:
        # main.go以外でのfmt.Print*を禁止、代わりにslogを使用
        - pattern: '^fmt\.Print'
        - pattern: '^print$'
        - pattern: '^println$'
        - pattern: '^panic$'
    godox:
      # TODO, OPT, etc. comments are fine to commit. Use FIXME comments for
      # temporary hacks, and use godox to prevent committing them.
      keywords: [FIXME]
    # 最近のディスプレイは広くなっているので、120から150へ変更。
    lll:
      line-length: 150
      tab-width: 4
    # カラム数制限を付けたら行が溢れたのでとりあえず80に設定
    funlen:
      lines: 80
      statements: 40
      ignore-comments: true
    # 10だと超えてしまうので、15に設定
    cyclop:
      max-complexity: 15

  exclusions:
    warn-unused: true
    rules:
      # テストファイルでは、関数の長さを制限しない
      - linters: [funlen]
        path: ".*_test\\.go$"
      # テストファイルでは、gosecの弱い乱数生成器警告を除外
      - linters: [gosec]
        path: ".*_test\\.go$"
        text: "G404"
      # main.goでのfmt.Print*の使用を許可
      - linters: [forbidigo]
        path: ".*main\\.go$"
        text: "use of `fmt\\.Print"
      
formatters:
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(grpc-errors) # Custom section: groups all imports with the specified Prefix.

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
